### ISSUE TITLE
IndexError: list index out of range in rtmpclient.py

### ISSUE THREAD

**Issue by PiotrMi** [theintencity/rtmplite#105]
Input: python rtmpclient.py "rtmp://62.113.210.250/medienasa-live/ok-magdeburg_high" file1.flv

produces following error:

Traceback (most recent call last):
  File "rtmpclient.py", line 36, in <module>
    import os, sys, traceback, time, urlparse, socket, multitask
  File "/root/rtmplite/multitask.py", line 149, in <module>
    __revision__ = int('$Revision$'.split()[1])
IndexError: list index out of range

**Comment by madovsky** [comment]
did you download the last version of rtmplite?

**Comment by PiotrMi** [comment]
yes, I cloned it an hour ago directly from github

**Comment by madovsky** [comment]
how do you call rtmpclient? throught rtmplite or directly?

**Comment by PiotrMi** [comment]
python rtmpclient.py "rtmp://62.113.210.250/medienasa-live/ok-magdeburg_high" file1.flv

this was my call, so yeah I called it directly

**Comment by madovsky** [comment]
I never tried to call directly rtmplcient.py.
always used siprtmp.py

**Comment by PiotrMi** [comment]
I followed the "documentation" inside rtmpclient.py where it said to call it directly. Maybe this documentation needs to updated?

**Comment by madovsky** [comment]
yes you can do it thanks

**Comment by theintencity** [comment]
Hi Piotr,

That line #149 in multitask.py is the ramnant of moving from SVN (google
code) to git (on github). It is not really needed.

You can just comment out that line in your code. Put a # at the beginning
of that line to comment it out in Python.

**Comment by theintencity** [comment]
I checked in the commented out multitask.py.

**Comment by madovsky** [comment]
ok nice, thanks
