### ISSUE TITLE
Adding custom SIP Headers to invite

### ISSUE THREAD

**Issue by waterjump** [theintencity/rtmplite#109]
Are there any good examples of passing a custom SIP header on an invite call?  I have been digging through this code and documentation for days and coming up short.  This is for use with Twilio.  See their details on "SipHeader_<name>" about halfway down this page.  https://www.twilio.com/docs/api/twiml/twilio_request

Thanks.

**Comment by madovsky** [comment]
standard SIP custom header prefix is sip_h_X-......
and works for me

**Comment by waterjump** [comment]
@madovsky Can you please direct me to the part of the rtmplite API where I can provide headers?

**Comment by ROBERT-MCDOWELL** [comment]
look at 
def _createRegister() in siprtmp_gevent.py or siprtmp.py

**Comment by waterjump** [comment]
Thank you.  Closing.
