### ISSUE TITLE
Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by carnado2008** [theintencity/rtmplite#114]
Every time I run it...it will show Missing parentheses in call to 'print'. I hope someone can show me somelight. Thank you.

**Comment by ROBERT-MCDOWELL** [comment]
rtmplite is still in python 2.x you probably use python 3.x
you can contribute to rtmplite and convert it in python 3.x by forking it.

**Comment by carnado2008** [comment]
> rtmplite is still in python 2.x you probably use python 3.x you can contribute to rtmplite and convert it in python 3.x by forking it.

TQ Sir for information.
